// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6GL8GI8lRTORYz_jcp5plBu9e1A3f98s',
    appId: '1:992162973894:web:7dc29da14475c62699efc7',
    messagingSenderId: '992162973894',
    projectId: 'joysper-homework',
    authDomain: 'joysper-homework.firebaseapp.com',
    storageBucket: 'joysper-homework.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwcgzjRulsOGwdm4pT0kdG4nRrjhzT5U',
    appId: '1:992162973894:android:6e687728c487b09699efc7',
    messagingSenderId: '992162973894',
    projectId: 'joysper-homework',
    storageBucket: 'joysper-homework.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cb7ygd1I5m3LvwJGLKIcXAPcwxU79qs',
    appId: '1:992162973894:ios:2ff53602b8b5c48299efc7',
    messagingSenderId: '992162973894',
    projectId: 'joysper-homework',
    storageBucket: 'joysper-homework.appspot.com',
    iosBundleId: 'com.example.joysperHomework1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cb7ygd1I5m3LvwJGLKIcXAPcwxU79qs',
    appId: '1:992162973894:ios:c626b0c700c2c50f99efc7',
    messagingSenderId: '992162973894',
    projectId: 'joysper-homework',
    storageBucket: 'joysper-homework.appspot.com',
    iosBundleId: 'com.example.joysperHomework1.RunnerTests',
  );
}
